const BRAND = {
  ink: '#0a0f18',
  muted: '#6b7280',
  border: '#e5e7eb',
  blue: '#2563eb',
  cyan: '#06b6d4',
  accent: '#67e8f9',
  white: '#f8fafc',
};

function drawLogoMark(doc, x, y, size) {
  const r = size * 0.2;
  const gradient = doc.linearGradient(x, y, x + size, y + size);
  gradient.stop(0, BRAND.blue).stop(0.55, '#3b82f6').stop(1, BRAND.cyan);
  doc.roundedRect(x, y, size, size, r).fill(gradient);

  const barH = size * 0.11;
  doc
    .fillColor(BRAND.white)
    .roundedRect(x + size * 0.28, y + size * 0.3, size * 0.44, barH, barH / 2)
    .fill();
  doc
    .fillColor(BRAND.white)
    .roundedRect(x + size * 0.45, y + size * 0.3, barH, size * 0.42, barH / 2)
    .fill();
  doc
    .fillColor(BRAND.accent)
    .circle(x + size * 0.64, y + size * 0.7, size * 0.055)
    .fill();
}

// Draws the server wordmark + logo mark top-right, a report title top-left,
// and a divider — returns the y-coordinate content should start below.
export function addBrandHeader(doc, { title, subtitle, serverName = 'Taxify' }) {
  const { width, margins } = doc.page;
  const logoSize = 26;
  const top = 32;
  const logoX = width - margins.right - logoSize;

  drawLogoMark(doc, logoX, top, logoSize);
  doc.font('Helvetica-Bold').fontSize(14).fillColor(BRAND.ink);
  const wordmark = serverName;
  const wordmarkWidth = doc.widthOfString(wordmark);
  doc.text(wordmark, logoX - 10 - wordmarkWidth, top + logoSize / 2 - 7);

  doc.font('Helvetica-Bold').fontSize(18).fillColor(BRAND.ink).text(title, margins.left, top, { width: 320 });
  if (subtitle) {
    doc.font('Helvetica').fontSize(10).fillColor(BRAND.muted).text(subtitle, margins.left, top + 22, { width: 320 });
  }

  const dividerY = top + logoSize + 14;
  doc
    .moveTo(margins.left, dividerY)
    .lineTo(width - margins.right, dividerY)
    .strokeColor(BRAND.border)
    .lineWidth(1)
    .stroke();

  return dividerY + 20;
}

export function addFooter(doc, serverName = 'Taxify') {
  const { width, height, margins } = doc.page;
  const y = height - margins.bottom + 12;
  doc
    .font('Helvetica')
    .fontSize(8)
    .fillColor(BRAND.muted)
    .text(`Generated by ${serverName} · ${new Date().toLocaleDateString()}`, margins.left, y, {
      width: width - margins.left - margins.right,
    });
}

export { BRAND };
